version: '3.9'

services:
  db:
    image: postgres:15
    container_name: spotify_postgres
    restart: always
    environment:
      POSTGRES_DB: spotify_db
      POSTGRES_USER: spotify_user
      POSTGRES_PASSWORD: spotify_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
